name: Build necromine and upload it to itch.io

on:
  push:
    branches:
      - deploy

env:
  BUTLER_API_KEY: Mx366LJQuD6dFVzMb7I9sKcZQHyZcbZrvtNgyIaL

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Download butler
        run: wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default -O butler.zip

      - name: Unzip buttler
        run: unzip butler.zip

      - name: Fix permissions
        run: chmod +x butler && chmod +x gradlew

      - name: Build jar
        run: ./gradlew desktop:jar

      - name: Build package image
        run: ./gradlew desktop:jpackageImage

      - name: Build deb/rpm
        run: ./gradlew desktop:jpackage

      - name: Fix file names
        run: mv desktop/build/lib/*.jar necromine_linux.jar && mv desktop/build/jpackage/*.deb necromine.deb && mv desktop/build/jpackage/*.rpm necromine.rpm

      - run: ./butler push necromine_linux.jar gadarts/necromine:linux-jar

      - run: ./butler push desktop/build/jpackage/desktop gadarts/necromine:linux-image

      - run: ./butler push necromine.deb gadarts/necromine:linux-deb
      - run: ./butler push necromine.rpm gadarts/necromine:linux-rpm
